strict.perms: false

filebeat.inputs:
  - type: log
    id: co_atc_logs
    enabled: true
    paths:
      - /logs/co_atc.log
      - /logs/simulador.log
      - /logs/inyector.log
      - /logs/adsb_events.log
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true
    fields:
      source: simulacion_adsb
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]
